+++
title = "exception"
+++
## Functions

### 


_____________________
#### Function [core](./../../core)::[exception](./../../core/exception)::`_yrt_exc_rethrow`
_____________________
### 


_____________________
#### Function [core](./../../core)::[exception](./../../core/exception)::`_yrt_exc_get_stack_trace`
_____________________
### 


_____________________
#### Function [core](./../../core)::[exception](./../../core/exception)::`_yrt_exc_resolve_stack_trace`
_____________________
### 


_____________________
#### Function [core](./../../core)::[exception](./../../core/exception)::`abort`
_____________________
### 


_____________________
#### Function [core](./../../core)::[exception](./../../core/exception)::`abort`
_____________________
### 


_____________________
#### Function [core](./../../core)::[exception](./../../core/exception)::`rethrow`
_____________________
### 


_____________________
#### Function [core](./../../core)::[exception](./../../core/exception)::`_yrt_throw_seg_fault`
_____________________
### 


_____________________
#### Function [core](./../../core)::[exception](./../../core/exception)::`_yrt_throw_runtime_abort`
_____________________


